# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_usercheckout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercheckout',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cart.Cart'),
        ),
    ]
