# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_auto_20160922_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercheckout',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
