# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_usercheckout_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercheckout',
            name='stars',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
