# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='color',
            field=models.CharField(blank=True, default='default', max_length=120, null=True),
        ),
    ]
