# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20160921_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='age',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Children', 'Children'), ('Adult', 'Adult')], default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='variation',
            name='gender',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Unisex', 'Unisex'), ('Male', 'Male'), ('Female', 'Female')], default='Unisex', max_length=100),
        ),
    ]
