# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SKU',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
