# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='caption',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
